"""Generate src/mathkids/_templates_embedded.py from templates/*.html.

The Cloudflare Workers bundle carries only .py modules, so Jinja can't load
template files from disk there. This bakes them into an importable dict.
wrangler runs it automatically before every dev/deploy (see "build" in
wrangler.jsonc); local uvicorn keeps reading the live files instead.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "src" / "mathkids" / "templates"
OUT = ROOT / "src" / "mathkids" / "_templates_embedded.py"


def main() -> None:
    entries = []
    for path in sorted(TEMPLATES.glob("*.html")):
        entries.append(f"    {path.name!r}: {path.read_text(encoding='utf-8')!r},")
    content = (
        '"""Generated by tools/embed_templates.py - do not edit."""\n\n'
        "TEMPLATES = {\n" + "\n".join(entries) + "\n}\n"
    )
    # Skip the write when nothing changed: wrangler's dev watcher re-runs this
    # build hook on file changes, so an unconditional write would loop forever.
    if OUT.exists() and OUT.read_text(encoding="utf-8") == content:
        print(f"Embedded templates up to date ({len(entries)} templates)")
        return
    OUT.write_text(content, encoding="utf-8")
    print(f"Embedded {len(entries)} templates -> {OUT}")


if __name__ == "__main__":
    main()
