"""Generate the modules the Workers bundle needs baked in.

- src/mathkids/_templates_embedded.py from templates/*.html: the Cloudflare
  Workers bundle carries only .py modules, so Jinja can't load template files
  from disk there.
- src/mathkids/_build_info.py with the short git commit hash, so the deployed
  app can show which code it was built from.

wrangler runs this automatically before every dev/deploy (see "build" in
wrangler.jsonc); local uvicorn reads the live template files and asks git
directly instead.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "src" / "mathkids" / "templates"
OUT = ROOT / "src" / "mathkids" / "_templates_embedded.py"
BUILD_INFO = ROOT / "src" / "mathkids" / "_build_info.py"


def _write(path: Path, content: str, label: str) -> None:
    # Skip the write when nothing changed: wrangler's dev watcher re-runs this
    # build hook on file changes, so an unconditional write would loop forever.
    if path.exists() and path.read_text(encoding="utf-8") == content:
        print(f"{label} up to date")
        return
    path.write_text(content, encoding="utf-8")
    print(f"Wrote {label} -> {path}")


def main() -> None:
    entries = []
    for path in sorted(TEMPLATES.glob("*.html")):
        entries.append(f"    {path.name!r}: {path.read_text(encoding='utf-8')!r},")
    _write(
        OUT,
        '"""Generated by tools/embed_templates.py - do not edit."""\n\n'
        "TEMPLATES = {\n" + "\n".join(entries) + "\n}\n",
        f"Embedded templates ({len(entries)})",
    )

    commit = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, cwd=ROOT
    ).stdout.strip() or "unknown"
    dirty = bool(
        subprocess.run(
            ["git", "status", "--porcelain"], capture_output=True, text=True, cwd=ROOT
        ).stdout.strip()
    )
    if dirty:
        commit += "+"  # uncommitted changes were part of this build
    _write(
        BUILD_INFO,
        '"""Generated by tools/embed_templates.py - do not edit."""\n\n'
        f"COMMIT = {commit!r}\n",
        f"Build info ({commit})",
    )


if __name__ == "__main__":
    main()
