"""Dump mathkids.db as INSERT statements for Cloudflare D1.

Usage:
    uv run python tools/export_d1.py            # reads mathkids.db, writes tools/d1_seed.sql
    npx wrangler d1 execute mathkids --remote --file tools/d1_seed.sql

Ids are exported explicitly so attempt.session_id references stay intact and —
because SQLite AUTOINCREMENT advances past explicitly-inserted ids — new
sessions continue numbering where the old ones left off, keeping the
``session_id * 1000 + i`` problem seeds unique.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "mathkids.db"
OUT = ROOT / "tools" / "d1_seed.sql"

# Insertion order: parents before children (no FK constraints today, but tidy).
TABLES = ["kid", "skill_state", "session", "attempt"]


def sql_literal(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    raise TypeError(f"unsupported value type: {type(v)!r}")


def main() -> None:
    conn = sqlite3.connect(f"file:{DB.as_posix()}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    lines = ["-- Generated by tools/export_d1.py — full dump of mathkids.db"]
    counts = {}
    for table in TABLES:
        rows = conn.execute(f"SELECT * FROM {table} ORDER BY rowid").fetchall()
        counts[table] = len(rows)
        if not rows:
            continue
        cols = ", ".join(rows[0].keys())
        lines.append(f"\n-- {table}: {len(rows)} rows")
        for r in rows:
            vals = ", ".join(sql_literal(v) for v in r)
            lines.append(f"INSERT INTO {table} ({cols}) VALUES ({vals});")
    conn.close()
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    total = sum(counts.values())
    print(f"Wrote {OUT} — {total} rows: " +
          ", ".join(f"{t}={n}" for t, n in counts.items()))


if __name__ == "__main__":
    main()
